### ISSUE TITLE
Connection establish problems between 2 agent through each endpoint using VON network

### ISSUE THREAD

**Issue by lemonpooh** [yunxi-zhang/ACAPy-Controller-Angular#2]
```
2022-07-30 11:10:09,164 aiohttp.access INFO 172.17.0.1 [30/Jul/2022:11:10:09 +0000] "POST /connections/receive-invitation?auto_accept=true HTTP/1.1" 200 757 "http://localhost:9001/api/doc" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.71"
2022-07-30 11:10:09,166 aries_cloudagent.transport.outbound.manager ERROR >>> Error when posting to: http://172.17.0.3:8000/; Error: (<class 'aiohttp.client_exceptions.ClientConnectorError'>, ClientConnectorError(ConnectionKey(host='172.17.0.3', port=8000, is_ssl=False, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None), ConnectionRefusedError(111, "Connect call failed ('172.17.0.3', 8000)")), <traceback object at 0x7fe188032808>); Re-queue failed message ...

```

```
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 936, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 798, in create_connection
    raise exceptions[0]
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/base_events.py", line 785, in create_connection
    yield from self.sock_connect(sock, address)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('172.17.0.3', 8000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aries_cloudagent/transport/outbound/http.py", line 81, in handle_message
    endpoint, data=payload, headers=headers
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 1004, in _create_direct_connection
    raise last_exc
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 986, in _create_direct_connection
    req=req, client_error=client_error)
  File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/site-packages/aiohttp/connector.py", line 943, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 172.17.0.3:8000 ssl:default [Connect call failed ('172.17.0.3', 8000)]
```

Hii, I am trying to establish connection between 2 agent by changing the sovrin testnet to local VON-network using local docker, however the endpoint of each agent seems cannot be connect. Even though the API is still able return back the responses.

**Comment by haneol97** [comment]
i having same problem 
--auto-accept-invites \
--auto-accept-requests \
--auto-ping-connection \
I added the above three parameters and performed /connections/create-invitation in inviter and /connecntions/receive-invitation in invitee on each agent, but it was still not connected
connection state of inviter is invitation
connection state of invitee is request  
I don't know what the problem is

**Comment by lemonpooh** [comment]
> i having same problem --auto-accept-invites --auto-accept-requests --auto-ping-connection I added the above three parameters and performed /connections/create-invitation in inviter and /connecntions/receive-invitation in invitee on each agent, but it was still not connected connection state of inviter is invitation connection state of invitee is request I don't know what the problem is

Hi, nice to know you having the same issue as me.
i have even try out changing 172.17.0.x to host.docker.internal:7000 (issuer), it will still not able to able to route to the endpoint connection. And i am running in windows env with docker desktop
Do you also try out this issue of connecting to endpoint url too?

**Comment by haneol97** [comment]
```
Hi, nice to know you having the same issue as me.
i have even try out changing 172.17.0.x to host.docker.internal:7000 (issuer), it will still not able to able to route to the endpoint connection. And i am running in windows env with docker desktop
Did you also try out this issue of connecting to endpoint url too?
Which OS env are you currently using to run ACA-py?
```

Attempting in mac OS env
I'll show you the code for the two agents

**agent acting as issuer**
```
docker run -p 7001:7001  --name issuer --network=von_von -it bcgovimages/aries-cloudagent:py36-1.16-0_0.6.0 start \
-l Issuer \
-it http 0.0.0.0 7000 \
-ot http \
--admin 0.0.0.0 7001 \
--admin-insecure-mode \
-e http://172.17.0.2:7000/ \
--genesis-url  http://172.20.0.1:9000/genesis \
--seed haneol00000000000000000000000000 \
--wallet-type indy \
--wallet-name issuerwallet \
--wallet-key issuerkey \
--log-level debug  \
--auto-provision \
--auto-accept-invites \
--auto-accept-requests \
--auto-ping-connection \
--tails-server-base-url http://172.17.0.5:9000
```

**agent acting as holder**
```
docker run -p 8001:8001  --name holder --network=von_von -it bcgovimages/aries-cloudagent:py36-1.16-0_0.6.0 start \
-l Holder \
-it http 0.0.0.0 8000 \
-ot http \
--admin 0.0.0.0 8001 \
--admin-insecure-mode \
-e http://172.17.0.3:8000/ \
--genesis-url http://172.20.0.1:9000/genesis \
--wallet-type indy \
--wallet-name holderwallet \
--wallet-key holderkey \
--log-level debug \
--auto-provision \
--auto-accept-invites \
--auto-accept-requests \
--auto-ping-connection
```

It's a code that was written by reference in the acapy repository
I tried the same way as host.docker.internal:7000 at first, but failed, so I'm trying the same way as 172.17.0.x, and the Docker network changed from bridge to von_von

**Comment by lemonpooh** [comment]
> > Hi, nice to know you having the same issue as me.
> > i have even try out changing 172.17.0.x to host.docker.internal:7000 (issuer), it will still not able to able to route to the endpoint connection. And i am running in windows env with docker desktop
> > Did you also try out this issue of connecting to endpoint url too?
> > Which OS env are you currently using to run ACA-py?
> 
> Attempting in mac OS env I'll show you the code for the two agents
> 
> **agent acting as issuer**
> 
> ```
> docker run -p 7001:7001  --name issuer --network=von_von -it bcgovimages/aries-cloudagent:py36-1.16-0_0.6.0 start \
> -l Issuer \
> -it http 0.0.0.0 7000 \
> -ot http \
> --admin 0.0.0.0 7001 \
> --admin-insecure-mode \
> -e http://172.17.0.2:7000/ \
> --genesis-url  http://172.20.0.1:9000/genesis \
> --seed issuer00000000000000000000000000 \
> --wallet-type indy \
> --wallet-name issuerwallet \
> --wallet-key issuerkey \
> --log-level debug  \
> --auto-provision \
> --auto-accept-invites \
> --auto-accept-requests \
> --auto-ping-connection \
> --tails-server-base-url http://172.17.0.5:9000
> ```
> 
> **agent acting as holder**
> 
> ```
> docker run -p 8001:8001  --name holder --network=von_von -it bcgovimages/aries-cloudagent:py36-1.16-0_0.6.0 start \
> -l Holder \
> -it http 0.0.0.0 8000 \
> -ot http \
> --admin 0.0.0.0 8001 \
> --admin-insecure-mode \
> -e http://172.17.0.3:8000/ \
> --genesis-url http://172.20.0.1:9000/genesis \
> --wallet-type indy \
> --wallet-name holderwallet \
> --wallet-key holderkey \
> --log-level debug \
> --auto-provision \
> --auto-accept-invites \
> --auto-accept-requests \
> --auto-ping-connection
> ```
> 
> It's a code that was written by reference in the acapy repository I tried the same way as host.docker.internal:7000 at first, but failed, so I'm trying the same way as 172.17.0.x, and the Docker network changed from bridge to von_von

Hii, I have the same issue when trying to run the shell script using Docker host. While, instead of docker host, we can run the agents in docker compose which it can detect the ip address automatically without required to assign the ip manually. And remove the `ACAPY_NO_LEDGER: "true"` if you decide to connect to von ledger. Here is the successful establish connection using docker-compose script. Try this out! It has work for me.

```
version: "3"
services:
  issuerConn:
    image: bcgovimages/aries-cloudagent:py36-1.16-0_0.6.0
    container_name: issuerConn
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://issuerConn:6010"
      ACAPY_LABEL: "IssuerConn"
      ACAPY_LOG_LEVEL: "info"
      ADMIN_PORT: "6011"
      AGENT_PORT: "6010"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 6011 \
        --inbound-transport http '0.0.0.0' 6010 \
        --outbound-transport http \ 
        --seed issuer00000000000000000000000000  \
        --wallet-type indy \
        --wallet-name issuerwallet \
        --wallet-key issuerkey \
        --auto-provision \
        --auto-accept-invites \
        --auto-accept-requests \
        --genesis-url 'http://host.docker.internal:9000/genesis' \
        --auto-ping-connection " \
        
        
    ]
    ports:
      - "6011:6011"

  holderConn:
    image: bcgovimages/aries-cloudagent:py36-1.16-0_0.6.0
    container_name: holderConn
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://holderConn:7010"
      ACAPY_LABEL: "HolderConn"
      ACAPY_LOG_LEVEL: "info"
      ADMIN_PORT: "7011"
      AGENT_PORT: "7010"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 7011 \
        --inbound-transport http '0.0.0.0' 7010 \
        --outbound-transport http \ 
        --wallet-type indy \
        --wallet-local-did \
        --wallet-name holderwallet \
        --wallet-key holderkey \
        --auto-provision \
        --auto-accept-invites \
        --auto-accept-requests \
        --genesis-url 'http://host.docker.internal:9000/genesis' \
        --auto-ping-connection "
    ]
    ports:
      - "7011:7011"

  verifierConn:
    image: bcgovimages/aries-cloudagent:py36-1.16-0_0.6.0
    container_name: verifierConn
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://verifierConn：8010"
      ACAPY_LABEL: "VerifierConn"
      ACAPY_LOG_LEVEL: "info"
      ADMIN_PORT: "8011"
      AGENT_PORT: "8010"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 8011 \
        --inbound-transport http '0.0.0.0' 8010 \
        --outbound-transport http \ 
        --wallet-type indy \
        --wallet-local-did \
        --wallet-name verifierwallet \
        --wallet-key verifierkey \
        --auto-provision \
        --auto-accept-invites \
        --auto-accept-requests \
        --genesis-url 'http://host.docker.internal:9000/genesis' \
        --auto-ping-connection "
    ]
    ports:
      - "8011:8011"
```



However, I am facing another error comes to issuing credentials ...😭 pls helpp

> issueCredential failed: Http failure response for http://localhost:6011/issue-credential-2.0/records/e61ef906-67ba-4fec-a5d5-cd23569193c6/issue: 400 Cred def id VV9pK5ZrLPRwYmotgACPkC:3:CL:15:passport has no active revocation registry.

**Comment by yunxi-zhang** [comment]
Hello @haneol97  and @lemonpooh, looks like you tried to run your local VON-networks and updated the shell script files in this repo. This repo is mainly a frontend app, it relies on your acapy agents, and your issue is related to acapy agent running. If you find it's hard to run acapy by yourself, please raise your tickets to the acapy repo.
